# Generated by Django 5.1 on 2026-06-07 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0017_apdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded vendor-bill document (PDF, JPG, PNG, TIFF, WebP).', upload_to='ap/%Y/%m/')),
                ('original_filename', models.CharField(help_text='Original filename as supplied by the uploader / email client.', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type reported by the client (e.g. application/pdf).', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('source', models.CharField(choices=[('upload', 'Manual upload'), ('email', 'Email attachment')], default='upload', help_text='How the document arrived.', max_length=16)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', help_text='Processing lifecycle stage.', max_length=16)),
                ('chain_id', models.CharField(blank=True, help_text='Cross-department chain ID — set when the bill.received BusEvent is dispatched.', max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Free-text notes — e.g. email subject + sender, or manual annotations.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('bus_event', models.OneToOneField(blank=True, help_text='The bill.received BusEvent dispatched for this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_document', to='accounting.busevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_documents', to='accounting.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='The user who uploaded the document (null for webhook ingestion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AP Inbound Document',
                'verbose_name_plural': 'AP Inbound Documents',
                'ordering': ['-received_at'],
            },
        ),
    ]
