# Generated by Django 5.1 on 2026-05-31 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Step 13 — RLS for the one tenant-scoped table in this app. Rule and
# Citation are GLOBAL (shipped with the product, shared by all tenants),
# so no policy. Only knowledge_tenantprocedure carries a tenant FK.
NEW_TENANT_TABLES = (
    'knowledge_tenantprocedure',
)


def add_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        cursor.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY;')
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint)
              WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
        """)


def remove_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_backfill_provenance_for_existing_jes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable id, e.g. 'syscohada-coa-class-2' or 'cgi-2025-tva-deductible'.", max_length=96, unique=True)),
                ('scope', models.CharField(choices=[('framework', 'Accounting framework'), ('tax_code', 'Tax code')], max_length=16)),
                ('jurisdiction', models.CharField(blank=True, help_text="e.g. 'OHADA', 'CMR', 'IFRS-global', or '' for N/A.", max_length=32)),
                ('framework', models.CharField(help_text="Framework/code + version, e.g. 'SYSCOHADA-2017', 'CGI-2025', 'IFRS'.", max_length=32)),
                ('knowledge_slice', models.CharField(blank=True, db_index=True, help_text='Encoding-catalogue slice id (K01–K20) for tracking.', max_length=8)),
                ('title', models.CharField(max_length=256)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, help_text="Short citation, e.g. 'SYSCOHADA Titre VII Ch.2 §41' or 'CGI 2025 art. 7'.", max_length=256)),
                ('source_text', models.TextField(blank=True, help_text='Full text of the cited passage.')),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text="When does this rule apply? e.g. {'transaction_type': 'fixed_asset_acquisition', 'asset_class': 'vehicles'}")),
                ('effects', models.JSONField(blank=True, default=dict, help_text="What does it do? e.g. {'depreciation_method': 'straight_line', 'useful_life_months': 48}")),
                ('examples', models.JSONField(blank=True, default=list)),
                ('confidence_floor', models.DecimalField(decimal_places=3, default=0.9, max_digits=4)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs expert review'), ('verified', 'Verified by expert')], default='needs_review', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['framework', 'knowledge_slice', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('reference', models.CharField(help_text="e.g. 'SYSCOHADA Titre VIII, Ch. 4, §94'.", max_length=256)),
                ('text', models.TextField(blank=True, help_text='The quoted passage.')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.rule')),
            ],
            options={
                'ordering': ['rule', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable id, unique per tenant, e.g. 'depr-vehicles-4y'.", max_length=96)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, help_text="Plain statement of the procedure, e.g. 'Vehicles depreciate straight-line over 4 years.'")),
                ('trigger_conditions', models.JSONField(blank=True, default=dict)),
                ('effects', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending validation'), ('validated', 'Validated — no framework conflict'), ('conflict', 'Conflicts with framework')], default='pending', max_length=16)),
                ('validation_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('overrides_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_by', to='knowledge.rule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='accounting.tenant')),
            ],
            options={
                'ordering': ['tenant', 'slug'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['framework', 'scope'], name='knowledge_r_framewo_58314f_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['knowledge_slice'], name='knowledge_r_knowled_83b581_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantprocedure',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_procedure_slug_per_tenant'),
        ),
        migrations.RunPython(
            add_rls_for_new_tables, remove_rls_for_new_tables, elidable=False,
        ),
    ]
