# Generated by Django 5.1.15 on 2026-06-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0016_bus_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Manual upload"),
                            ("email", "Email-to-bill"),
                            ("api", "API / connector"),
                        ],
                        db_index=True,
                        default="upload",
                        help_text="How the document entered the system.",
                        max_length=12,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("vendor_bill", "Vendor bill"),
                            ("vendor_invoice", "Vendor invoice"),
                            ("purchase_order", "Purchase order"),
                            ("customer_invoice", "Customer invoice"),
                            ("credit_note", "Credit note"),
                            ("payment", "Payment advice"),
                            ("bank_statement", "Bank statement"),
                            ("asset_acquisition", "Asset acquisition"),
                            ("journal_entry", "Journal entry"),
                            ("payroll", "Payroll pack"),
                            ("other", "Other / unclassified"),
                        ],
                        default="vendor_bill",
                        help_text="Drives departmental routing (vendor_bill → D01 AP, etc.).",
                        max_length=24,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="The uploaded / emailed PDF or image.",
                        null=True,
                        upload_to="documents/%Y/%m/",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Content hash — used to detect duplicate uploads.",
                        max_length=64,
                    ),
                ),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=512)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received — awaiting routing"),
                            ("routed", "Routed to department inbox"),
                            ("unrouted", "Unrouted — needs manual triage"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                    ),
                ),
                (
                    "routed_dept",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D00", "Controller"),
                            ("D01", "AP — Accounts Payable"),
                            ("D02", "AR — Accounts Receivable"),
                            ("D03", "Treasury"),
                            ("D04", "Fixed Assets"),
                            ("D05", "GL — General Ledger"),
                            ("D06", "Tax"),
                            ("D07", "Payroll"),
                            ("D08", "Inventory"),
                            ("D09", "Reporting"),
                            ("D10", "Cost Accounting"),
                            ("D11", "FP&A"),
                            ("dispatcher", "Dispatcher (routing)"),
                            ("system", "System (non-departmental)"),
                        ],
                        db_index=True,
                        help_text="Department this document was routed to (blank if unrouted).",
                        max_length=12,
                    ),
                ),
                (
                    "chain_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UUID linking this document to its causal event chain (Step 44).",
                        max_length=64,
                    ),
                ),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("routed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounting.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "routed_dept", "status"],
                        name="ingest_docu_tenant__baf6ab_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="ingest_docu_tenant__4b87e8_idx",
                    ),
                    models.Index(
                        fields=["chain_id"], name="ingest_docu_chain_i_8b1a82_idx"
                    ),
                ],
            },
        ),
    ]
