# Generated by Django 5.1 on 2026-05-13 18:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(help_text='ISO code, e.g. XAF, EUR, USD', max_length=8, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.IntegerField(default=2, help_text='0 for XAF, 2 for EUR/USD')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('legal_name', models.CharField(blank=True, max_length=256)),
                ('tax_id', models.CharField(blank=True, max_length=32, verbose_name='Tax ID / NIU')),
                ('company_registry', models.CharField(blank=True, max_length=64, verbose_name='RCCM')),
                ('street', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('fiscal_year_start_month', models.IntegerField(default=1, help_text='1=January')),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('receivable', 'Receivable'), ('asset_cash', 'Bank and Cash'), ('asset_current', 'Current Assets'), ('asset_non_current', 'Non-current Assets'), ('asset_prepayments', 'Prepayments'), ('asset_fixed', 'Fixed Assets'), ('payable', 'Payable'), ('liability_credit_card', 'Credit Card'), ('liability_current', 'Current Liabilities'), ('liability_non_current', 'Non-current Liabilities'), ('equity', 'Equity'), ('equity_unaffected', 'Current Year Earnings'), ('income', 'Income'), ('income_other', 'Other Income'), ('expense', 'Expenses'), ('expense_depreciation', 'Depreciation'), ('expense_direct_cost', 'Cost of Revenue'), ('expense_other', 'Other Expenses'), ('off_balance_sheet', 'Off-Balance Sheet')], max_length=32)),
                ('reconcile', models.BooleanField(default=False, help_text='Allow reconciling lines on this account (typical for AR/AP)')),
                ('deprecated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(help_text='Short code, e.g. VEN, ACH, BNK, OD', max_length=8, unique=True)),
                ('type', models.CharField(choices=[('sale', 'Sales'), ('purchase', 'Purchases'), ('cash', 'Cash'), ('bank', 'Bank'), ('general', 'General / Miscellaneous')], max_length=16)),
                ('sequence_prefix', models.CharField(default='', help_text='e.g. "VEN/", "ACH/"', max_length=16)),
                ('next_sequence', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('default_account', models.ForeignKey(blank=True, help_text='Default account for entries in this journal (e.g. the bank account for a BNK journal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('purchase_date', models.DateField()),
                ('in_service_date', models.DateField(help_text='Depreciation starts on this date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('useful_life_months', models.IntegerField(help_text='e.g. 60 for 5 years')),
                ('method', models.CharField(choices=[('straight_line', 'Straight-line'), ('declining', 'Declining balance')], default='straight_line', max_length=16)),
                ('declining_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Annual rate, e.g. 0.20 for 20%. Used only for declining-balance method.', max_digits=5)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_use', 'In use'), ('fully_depreciated', 'Fully depreciated'), ('disposed', 'Disposed')], default='draft', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='Contra-asset (typically class 28xx)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('asset_account', models.ForeignKey(help_text='Class 2 — the asset (e.g. 244x for office equipment)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('depreciation_expense_account', models.ForeignKey(help_text='Class 68xx — depreciation expense', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('depreciation_journal', models.ForeignKey(help_text='Journal where periodic depreciation entries will post (typically OD/General)', on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_assets', to='accounting.journal')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Auto-assigned on posting from the journal sequence', max_length=64)),
                ('date', models.DateField()),
                ('ref', models.CharField(blank=True, max_length=128, verbose_name='Reference')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journal')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='End of the period being depreciated')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('posted', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_lines', to='accounting.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['asset', 'period_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('partner_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('both', 'Customer & Vendor'), ('other', 'Other')], default='customer', max_length=16)),
                ('is_company', models.BooleanField(default=True)),
                ('tax_id', models.CharField(blank=True, max_length=32, verbose_name='Tax ID / NIU')),
                ('company_registry', models.CharField(blank=True, max_length=64, verbose_name='RCCM')),
                ('street', models.CharField(blank=True, max_length=256)),
                ('street2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('zip', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.CharField(blank=True, max_length=256)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_payable', models.ForeignKey(blank=True, help_text='Default AP account for this vendor (usually 401x)', limit_choices_to={'type': 'payable'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners_as_payable', to='accounting.account')),
                ('account_receivable', models.ForeignKey(blank=True, help_text='Default AR account for this customer (usually 411x)', limit_choices_to={'type': 'receivable'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners_as_receivable', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Description / memo', max_length=256)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('reconciled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('reconciled_with', models.ManyToManyField(blank=True, to='accounting.journalentryline')),
                ('partner', models.ForeignKey(blank=True, help_text='Required for receivable/payable lines (drives the AR/AP sub-ledger)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='accounting.partner')),
            ],
            options={
                'ordering': ['entry', 'id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.partner'),
        ),
    ]
