# Generated by Django 5.1 on 2026-05-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier; becomes subdomain', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('legal_name', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, help_text='e.g. Cameroon', max_length=64)),
                ('business_type', models.CharField(choices=[('services', 'Services'), ('goods', 'Goods'), ('both', 'Services & Goods')], default='both', max_length=16)),
                ('fiscal_year_start_month', models.IntegerField(default=1, help_text='1=January')),
                ('tax_id', models.CharField(blank=True, max_length=32, verbose_name='Tax ID / NIU')),
                ('company_registry', models.CharField(blank=True, max_length=64, verbose_name='RCCM')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Default reporting currency (e.g. XAF for OHADA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who created the tenant and pays the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_lines_for_tenant', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_lines', to='accounting.tenant'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='accounting.tenant'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='accountant', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounting.tenant')),
            ],
            options={
                'ordering': ['tenant', 'user'],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
