# Generated by Django 5.1 on 2026-05-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_backfill_elite_advisors_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='depreciationline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_lines_for_tenant', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='code',
            field=models.CharField(help_text='Short code, e.g. VEN, ACH, BNK, OD', max_length=8),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_lines', to='accounting.tenant'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='accounting.tenant'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_account_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_fixedasset_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_journal_code_per_tenant'),
        ),
    ]
