# Generated by Django 5.1 on 2026-05-17 11:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tighten_tenant_fk_and_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Auto-assigned on posting from the sales journal sequence', max_length=32)),
                ('date', models.DateField(help_text='Invoice date')),
                ('due_date', models.DateField(help_text='Payment due')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage withheld at source by the buyer (e.g. 10.00 for 10%)', max_digits=6)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_withholding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('journal', models.ForeignKey(help_text='Sales journal used for posting', limit_choices_to={'type': 'sale'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='accounting.journal')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Set once the invoice is posted to the GL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_post', to='accounting.journalentry')),
                ('partner', models.ForeignKey(limit_choices_to={'partner_type__in': ['customer', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='accounting.partner')),
                ('payment_entry', models.ForeignKey(blank=True, help_text='Set once payment has been recorded', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_payment', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10, help_text='Display order on the invoice')),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT percentage on this line (e.g. 19.25 for OHADA standard rate)', max_digits=6)),
                ('account', models.ForeignKey(help_text='Revenue account (e.g. 70x in SYSCOHADA)', limit_choices_to={'type__in': ['income', 'income_other']}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.customerinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_lines', to='accounting.tenant')),
            ],
            options={
                'ordering': ['invoice', 'sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'number'), name='unique_invoice_number_per_tenant'),
        ),
    ]
