# Generated by Django 5.1 on 2026-05-17 14:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_customerinvoice_customerinvoiceline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Internal reference, auto-assigned on posting from the purchases journal sequence', max_length=32)),
                ('vendor_reference', models.CharField(blank=True, help_text="The vendor's own invoice number (printed on their PDF)", max_length=64)),
                ('date', models.DateField(help_text='Bill date')),
                ('due_date', models.DateField(help_text='Payment due')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage WE withhold from this vendor at source to remit to the tax authority (e.g. 5.50 for 5.5%)', max_digits=6)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_withholding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency')),
                ('journal', models.ForeignKey(help_text='Purchases journal used for posting', limit_choices_to={'type': 'purchase'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bills', to='accounting.journal')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bill_post', to='accounting.journalentry')),
                ('partner', models.ForeignKey(limit_choices_to={'partner_type__in': ['vendor', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bills', to='accounting.partner')),
                ('payment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bill_payment', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_bills', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10)),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT percentage on this line', max_digits=6)),
                ('account', models.ForeignKey(help_text='Expense or asset account being debited (e.g. 6xx in SYSCOHADA)', limit_choices_to={'type__in': ['expense', 'expense_direct_cost', 'expense_other', 'asset_current', 'asset_non_current', 'asset_fixed']}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.supplierbill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_bill_lines', to='accounting.tenant')),
            ],
            options={
                'ordering': ['bill', 'sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierbill',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'number'), name='unique_supplier_bill_number_per_tenant'),
        ),
    ]
