# Generated by Django 5.1 on 2026-05-17 15:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_supplierbill_supplierbillline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Balance per the bank at start of period', max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Balance per the bank at end of period', max_digits=18)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('reconciled', 'Reconciled')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(help_text='Bank or cash journal this statement covers', limit_choices_to={'type__in': ['bank', 'cash']}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.journal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=512)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive = inflow, negative = outflow', max_digits=18)),
                ('state', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('posted', 'Posted')], default='unmatched', max_length=16)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('generated_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_from_bank_lines', to='accounting.journalentry')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_entry_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_bank_lines', to='accounting.journalentryline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_lines', to='accounting.tenant')),
            ],
            options={
                'ordering': ['statement', 'sequence', 'transaction_date', 'id'],
            },
        ),
    ]
