# Generated by Django 5.1 on 2026-05-31 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Step 6 — RLS extension for the new tenant-scoped tables introduced here.
# Period and PeriodLock both carry a `tenant` FK and so participate in the
# defence-in-depth Row-Level Security pattern established by 0008. FxRate
# is intentionally global (no tenant FK), so no policy applied.
NEW_TENANT_TABLES = (
    'accounting_period',
    'accounting_periodlock',
)


def add_rls_for_new_tables(apps, schema_editor):
    """No-op on SQLite; on Postgres, install the standard tenant_isolation
    policy (same predicate as 0008_postgres_rls) on the new tables."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        cursor.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY;')
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint)
              WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
        """)


def remove_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_postgres_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Period identifier — e.g. '2026-05' for May 2026, 'FY2026-Q2' for the second quarter of fiscal year 2026.", max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('in_progress', 'Close in progress'), ('closed', 'Closed')], default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-end_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock')], max_length=8)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_events', to='accounting.period')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_lock_events', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixing_date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Quote per 1 unit of base. E.g. base=EUR quote=XAF → ~655.957 means 1 EUR = 655.957 XAF.', max_digits=20)),
                ('source', models.CharField(blank=True, help_text="Origin of the fixing — 'BCEAO', 'ECB', 'manual', etc.", max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_as_base', to='accounting.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_as_quote', to='accounting.currency')),
            ],
            options={
                'ordering': ['-fixing_date', '-id'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-fixing_date'], name='accounting__base_cu_da30d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'fixing_date'), name='unique_fx_rate_per_pair_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_period_code_per_tenant'),
        ),
        migrations.RunPython(
            add_rls_for_new_tables, remove_rls_for_new_tables, elidable=False,
        ),
    ]
