# Generated by Django 5.1 on 2026-05-31 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Step 7 — RLS extension for the five new tenant-scoped tables.
# All five carry a `tenant` FK and participate in the defence-in-depth
# Row-Level Security pattern established by 0008.
NEW_TENANT_TABLES = (
    'accounting_agentrun',
    'accounting_agenttoolcall',
    'accounting_erpconnection',
    'accounting_erpoperation',
    'accounting_provenance',
)


def add_rls_for_new_tables(apps, schema_editor):
    """No-op on SQLite; on Postgres install the tenant_isolation policy."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        cursor.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY;')
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint)
              WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
        """)


def remove_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_period_periodlock_fxrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('D00', 'Controller'), ('D01', 'AP — Accounts Payable'), ('D02', 'AR — Accounts Receivable'), ('D03', 'Treasury'), ('D04', 'Fixed Assets'), ('D05', 'GL — General Ledger'), ('D06', 'Tax'), ('D07', 'Payroll'), ('D08', 'Inventory'), ('D09', 'Reporting'), ('D10', 'Cost Accounting'), ('D11', 'FP&A'), ('dispatcher', 'Dispatcher (routing)'), ('system', 'System (non-departmental)')], max_length=16)),
                ('task', models.CharField(help_text='Short label of what this run did, e.g. "classify_vendor_bill"', max_length=128)),
                ('chain_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('proposed', 'Proposed — awaiting approval'), ('approved', 'Approved'), ('executed', 'Executed — action complete'), ('rejected', 'Rejected by reviewer'), ('failed', 'Failed'), ('skipped', 'Skipped — kill switch or capacity cap')], default='pending', max_length=16)),
                ('llm_model', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='0.000 → 1.000', max_digits=4, null=True)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('tool', models.CharField(help_text='Tool name, e.g. "erp.post_je", "knowledge.retrieve"', max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='accounting.agentrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_calls', to='accounting.tenant')),
            ],
            options={
                'ordering': ['agent_run', 'sequence', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. "Production Odoo"', max_length=64)),
                ('vendor', models.CharField(choices=[('odoo', 'Odoo'), ('sage', 'Sage Saari'), ('sap_b1', 'SAP Business One'), ('dynamics_365_bc', 'Dynamics 365 Business Central'), ('quickbooks', 'QuickBooks Online'), ('manual', 'Manual / no ERP (standalone mode)')], max_length=32)),
                ('version', models.CharField(blank=True, help_text='e.g. "17.0"', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, help_text='URL, port, db name, env-var names referencing secrets.')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('health', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degraded'), ('down', 'Down'), ('unconfigured', 'Unconfigured')], default='unconfigured', max_length=16)),
                ('last_healthcheck_at', models.DateTimeField(blank=True, null=True)),
                ('last_healthcheck_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary connection when tenant has multiple ERPs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_connections', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ERPOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(help_text='CAP.NN code from the capability registry, e.g. "CAP.03"', max_length=16)),
                ('method', models.CharField(blank=True, help_text='Vendor-specific endpoint, e.g. "account.move.create"', max_length=64)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='IDs assigned by the remote ERP, e.g. {"move_id": 1234}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('success', 'Success'), ('partial', 'Partial success'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='accounting.erpconnection')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_operations', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_operations', to='accounting.tenant')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_operations', to='accounting.agenttoolcall')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual entry by human'), ('agent', 'Agent-proposed action'), ('imported', 'Imported (CSV / bank feed / OCR)'), ('system', 'System-generated (depreciation, FX, accruals)'), ('migration', 'Created by a data migration')], default='manual', max_length=16)),
                ('chain_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_records', to='accounting.agentrun')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_records', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['tenant', 'department', 'status'], name='accounting__tenant__0d498e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['tenant', 'chain_id'], name='accounting__tenant__90e0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='erpoperation',
            index=models.Index(fields=['tenant', 'capability', 'status'], name='accounting__tenant__74a1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='erpoperation',
            index=models.Index(fields=['tenant', 'connection', '-started_at'], name='accounting__tenant__ff1f36_idx'),
        ),
        migrations.AddIndex(
            model_name='provenance',
            index=models.Index(fields=['tenant', 'chain_id'], name='accounting__tenant__1df55c_idx'),
        ),
        migrations.AddIndex(
            model_name='provenance',
            index=models.Index(fields=['tenant', 'source'], name='accounting__tenant__60425a_idx'),
        ),
        migrations.RunPython(
            add_rls_for_new_tables, remove_rls_for_new_tables, elidable=False,
        ),
    ]
