# Generated by Django 5.1 on 2026-05-31 10:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# Step 8 — RLS extension for the new tenant-scoped subscription table.
NEW_TENANT_TABLES = (
    'accounting_tenantdepartmentsubscription',
)


def add_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        cursor.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY;')
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint)
              WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
        """)


def remove_rls_for_new_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    cursor = schema_editor.connection.cursor()
    for table in NEW_TENANT_TABLES:
        cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation ON {table};')
        cursor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_agentrun_agenttoolcall_erpconnection_erpoperation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accounting_framework',
            field=models.CharField(choices=[('SYSCOHADA-2017', 'SYSCOHADA Révisé (2017)'), ('IFRS', 'IFRS'), ('OTHER', 'Other / custom')], default='SYSCOHADA-2017', help_text="Which accounting framework's rules the agent applies for this tenant. Drives knowledge-layer rule selection.", max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_enabled',
            field=models.BooleanField(default=False, help_text='Master kill switch (R-safety). When off, no department agent takes any automated action for this tenant — work still queues but nothing auto-executes. Off by default; a tenant explicitly opts in.'),
        ),
        migrations.CreateModel(
            name='TenantDepartmentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('D00', 'Controller'), ('D01', 'AP — Accounts Payable'), ('D02', 'AR — Accounts Receivable'), ('D03', 'Treasury'), ('D04', 'Fixed Assets'), ('D05', 'GL — General Ledger'), ('D06', 'Tax'), ('D07', 'Payroll'), ('D08', 'Inventory'), ('D09', 'Reporting'), ('D10', 'Cost Accounting'), ('D11', 'FP&A')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('auto_action_cap', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Max amount the agent may auto-post in this department without human approval. 0 = always require approval.', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_approver', models.ForeignKey(blank=True, help_text="Human who reviews this department's approval queue. Leave blank to use the tenant's default approver.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_for_departments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_subscriptions', to='accounting.tenant')),
            ],
            options={
                'ordering': ['tenant', 'department'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'department'), name='unique_department_subscription_per_tenant')],
            },
        ),
        migrations.RunPython(
            add_rls_for_new_tables, remove_rls_for_new_tables, elidable=False,
        ),
    ]
