# Generated by Django 5.1 on 2026-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_backfill_provenance_for_existing_jes'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpconnection',
            name='secret_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='erpconnection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Non-secret connection settings: url, db, username.'),
        ),
    ]
