# Generated by Django 5.1 on 2026-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_erpconnection_secret_ciphertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('success', 'Success'), ('partial', 'Partial success'), ('failed', 'Failed'), ('escalated', 'Escalated'), ('rolled_back', 'Rolled back')], default='pending', max_length=16),
        ),
    ]
