# Generated by Django 5.1 on 2026-06-05 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_erpoperation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(choices=[('D00', 'Controller'), ('D01', 'AP — Accounts Payable'), ('D02', 'AR — Accounts Receivable'), ('D03', 'Treasury'), ('D04', 'Fixed Assets'), ('D05', 'GL — General Ledger'), ('D06', 'Tax'), ('D07', 'Payroll'), ('D08', 'Inventory'), ('D09', 'Reporting'), ('D10', 'Cost Accounting'), ('D11', 'FP&A'), ('dispatcher', 'Dispatcher (routing)'), ('system', 'System (non-departmental)')], help_text='Department whose agent created this proposal.', max_length=12)),
                ('action', models.CharField(help_text='Human-readable description of the proposed action.', max_length=255)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Event payload / extracted document that triggered the proposal.')),
                ('specialist_results', models.JSONField(blank=True, default=list, help_text='Outputs from each specialist in the pipeline (ok, output, error).')),
                ('chain_id', models.CharField(blank=True, db_index=True, help_text='UUID linking all events in the same causal chain (Step 44).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting review'), ('approved', 'Approved'), ('auto_approved', 'Auto-approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated — needs senior review'), ('executed', 'Executed — posted to ERP'), ('execution_failed', 'Execution failed')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Optional comment from the reviewer (required on rejection).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The human who approved or rejected this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_queue_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_queue_items', to='accounting.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'dept_code', 'status'], name='accounting__tenant__4845f4_idx'), models.Index(fields=['tenant', 'status', '-created_at'], name='accounting__tenant__99b3b9_idx'), models.Index(fields=['chain_id'], name='accounting__chain_i_722cfd_idx')],
            },
        ),
    ]
