# Generated by Django 5.1 on 2026-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_bus_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='busevent',
            new_name='accounting__tenant__3734a3_idx',
            old_name='accounting_bus_evt_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='busevent',
            new_name='accounting__tenant__ac00ec_idx',
            old_name='accounting_bus_evt_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='busevent',
            new_name='accounting__chain_i_c3a440_idx',
            old_name='accounting_bus_evt_chain_id_idx',
        ),
    ]
